In [1]:
import numpy as np

In [63]:
# Simple ways to init arrays
a = np.array([1, 2, 3], dtype='int16')
b = np.arange(3)
zeros = np.zeros((3,))
ones = np.ones((3,))
empties = np.empty((3,))
full = np.full((3,), 10)
full

array([10, 10, 10])

In [19]:
# Properties of ndarray

# shape
# ndim
# itemsize
# size
# nbytes = size * itemsize

In [20]:
# Get number of dimensions
a.ndim

1

In [21]:
# Get shape
a.shape

(3,)

In [23]:
# Get uniform datatype
a.dtype

dtype('int16')

In [26]:
# Get size of single item/element
a.itemsize # 2 bytes since int16

2

In [27]:
# Get number of elements
a.size

3

In [30]:
# To derive total memory size of array
# This works since ndarrays store uniform datatypes
a.size * a.itemsize == a.nbytes

True

In [31]:
# Accessing/Changing elements, rows, columns

6

In [33]:
a = np.arange(0,15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
# Get specific element using bracket notation
# Get 11 in row 3, column 2
# However since row,column indexing starts from 0
# We want a(2,1)
a[2,1]

11

In [44]:
# Get 0th row
# Since raw is multi-element returns ndarray
# Interestingly to access rows : is not necessary to be put to colımns
# But for column access we need therefore for uniformity always put :
a[0,:]

array([0, 1, 2, 3, 4])

In [45]:
# Get 0th column
a[:,0]

array([ 0,  5, 10])

In [50]:
# Get sub array
# From 6 to 8
# From 11 to 13
# That is upper,left = (1,1)
# Lower,right = (2,3)

a[1:3,1:4] # note that : is right open, does not include last element

array([[ 6,  7,  8],
       [11, 12, 13]])

In [52]:
# change elements from (1,1) to (2,3)
a[1:3,1:4] = np.arange(6).reshape((2,3))
a

In [57]:
# Question is it possible to assign with builting sequences
a[1:3,1:4] = [[6,7,8],[11,12,13]]
a
# Seems like so

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
# Axis numbering

# Row is 0th
# Column is 1st
# 3rd axis is 2nd
# so and so forth

# This follows bracket ordering
# Ex.

dd = np.array([
    [[1,2,3],
     [4,5,6]],
    
    [[7,8,9],
     [10,11,12]]
])

In [61]:
# Then algorithm for accessing in a k-dimensional array
# Index from right to left, is equivalent to working from outside in
# Get 8 from dd

dd[1, 0, 1]

8

In [68]:
# Question create an array full of 3s of the dd shape

# 2 ways use full, or full_like

issame = np.full(dd.shape, 3) == np.full_like(dd, 3)
issame

array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [69]:
# This is another point == works elementwise
# Therefore for deep comparsion take-and of each element
# np.all is equivalent to sum, but operation is and
# since for same arrays each element must be same
# We can take all of elementwise comparison
np.all(issame)

True

In [76]:
# To work with wimilar idea we need to take the floating point errors in account
# use for allclose for deterministic behaviour

np.allclose(np.full((3,3), 3.0), np.full((3,3), 3.0))
# Tolerance atol
np.allclose(np.full((3,3), 4.0), np.full((3,3), 3.0), atol = 1.0)


True

In [98]:
# Instead, of these prefer using default_generator
np.random.seed(0)
np.random.rand(2,2) # variadic function, shape is given as arguments
np.random.seed(0)
np.random.random((2,2)) #shape is given as tuple

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [109]:
# Random number generation proper way

rng = np.random.default_rng(0)

In [110]:
print(rng.normal(0,1))
rng = np.random.default_rng(0)
print(rng.normal())

0.1257302210933933
0.1257302210933933


In [114]:
rng.normal(2, 2, size = (2,2))

array([[1.36739969, 2.82326107],
       [4.08502674, 1.74293067]])

In [122]:
# rng.integers works with replacement
# This is basically equivalent to following
rng = np.random.default_rng(0)
rng.integers(0, 10, size = 11, endpoint=True)

array([9, 7, 5, 2, 3, 0, 0, 0, 1, 8, 7])

In [123]:
rng = np.random.default_rng(0)
rng.choice(range(0,11), size = 11)

array([9, 7, 5, 2, 3, 0, 0, 0, 1, 8, 7])

In [129]:
rng = np.random.default_rng(0)
# equivalent to uniform in following cell
rng.random(5)

array([0.63696169, 0.26978671, 0.04097352, 0.01652764, 0.81327024])

In [130]:
rng = np.random.default_rng(0)
rng.uniform(0,1,5)

array([0.63696169, 0.26978671, 0.04097352, 0.01652764, 0.81327024])

In [136]:
rng.shuffle(x:=[1,2,3])
x # returns the permutation of the original

[3, 2, 1]

In [147]:
# Permute rows or columns
# permute returns a new array
# While shuffle works in-place
rng = np.random.default_rng(0)
rng.permutation(np.arange(15).reshape(3,5), axis = 0)

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [148]:
rng = np.random.default_rng(0)
rng.shuffle(x:=np.arange(15).reshape(3,5))
x

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [149]:
# Identity
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [157]:
arr = np.array([[1,2,3],[4,5,6]])
np.repeat(arr, 2) # flattens and repeats each element

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [159]:
# Problem: create an array of shape=(3,5) where each column is 1,2,3
np.repeat(np.arange(1,4).reshape(3,1),5,axis = 1)
#IDEA create a col vector and repeat its columns

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [188]:
# Compare repeat and tile
r = np.arange(1,5)
# Repeat repeats the elements
print(np.repeat(r, 2))
# Tile repeats the array
print(np.tile(r, 2))

# Use acordingly
# I belive tile is more intiutive
# eg. For the problem above

np.tile(np.array([1,2,3]).reshape(3,1), 5)

[1 1 2 2 3 3 4 4]
[1 2 3 4 1 2 3 4]


array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [153]:
# Return set of elements
np.unique(np.array([1,2,3,4,5,1,2,3,4,5,1,1,2,2,3,4,5,5,5]))

array([1, 2, 3, 4, 5])

In [163]:
arr = np.ones((5,5), dtype='int')
zeros = np.zeros((3,3))
arr[1:4,1:4] = zeros
arr[2,2] = 9
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [166]:
# question what happens when we change (0,0) element of zeros
# to arr?

zeros[0,0] = 666666
zeros

array([[666666.,      0.,      0.],
       [     0.,      0.,      0.],
       [     0.,      0.,      0.]])

In [168]:
arr # nothing changed

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [180]:
# Create a copy of a

a = np.arange(1,10)
a
b = a.copy()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
# Mathematics

# Basic 4

a + a
a - a
a * a
a / a

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [183]:
T = np.full((3,3), True)
F = np.full((3,3), False)

In [197]:
# In place operations

a += 1
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [198]:
# exponentiation
a**2

array([  4,   9,  16,  25,  36,  49,  64,  81, 100])

In [205]:
# exponentiating a constant
2**a

array([   4,    8,   16,   32,   64,  128,  256,  512, 1024])

In [202]:
# square root
np.sqrt(a**2)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [206]:
# all types of logatihms
np.log2(2**a)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [218]:
# trigonemetric functions
angles = (np.array([0,45,90])/360)*np.pi*2
np.sin(angles)

array([0.        , 0.70710678, 1.        ])

In [220]:
# Matrix multiplication

np.arange(1,10).reshape(3,3) @ np.identity(3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [221]:
# determinant

np.linalg.det(np.identity(100))

1.0

In [224]:
# Stats
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [232]:
print("Min = ",np.min(data))
print("Max = ",np.max(data))
print("Sum = ",np.sum(data))
print("Mean = ",np.mean(data))
print("Median = ",np.median(data))

Min =  1
Max =  9
Sum =  45
Mean =  5.0
Median =  5.0


In [240]:
# More on sum
# Only summing rows or columns are possible

print(np.sum(data, axis=0)) 
print(np.sum(data, axis=1))


[12 15 18]
[ 6 15 24]


In [241]:
# Reorginize

a = np.zeros((3,3))
b = np.ones((3,3))

print(a)
print(b)
print(np.vstack([a,b]))
print(np.hstack([a,b]))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [247]:
# Different indexing approaches

# Similar to :, we can directly give lists, or tuples
print(data)
data[[0,2],:]

# Or can index by masking with booleans

b = data > 5
print(b)
data[b]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True  True  True]]


array([6, 7, 8, 9])

In [251]:
# Any is the analogus of all for or operation
# Find if there is a number less than or equal to 2 in a row
np.any(data <= 2, axis= 0)
# IDEA compare to 2, and apply any in row direction(to each col)

array([ True,  True, False])

In [256]:
# Numbers greater than 2 but less than 7

~((data > 2) & (data < 7)) # not is ~

array([[ True,  True, False],
       [False, False, False],
       [ True,  True,  True]])

In [260]:
n = np.arange(1, 31).reshape(6,5)
n[2:4, 0:2]
np.diag(n[0:4, 1:5])
n[[0,4,5], 3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])